backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blogs"
    label: "Blogs & Articles"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Short Excerpt / Summary", name: "excerpt", widget: "text"}
      - {label: "Body Content", name: "body", widget: "markdown"}